@startuml
!include skatt.iuml


state Ref <<OS1>>: version: prod
state Prod <<OS1>> : version : 1.2.3-b1.5.3-flange-8.153.18
Prod:releaseTo : prod


state DockerRegistry<<OS4>> : 123bca: prod
DockerRegistry: 123bca: 1.2.3-b1.5.3-flange-8.153.18

Prod -up-> DockerRegistry : lytter på :prod
Ref -up-> DockerRegistry : lytter på :prod



@enduml
